name: Merge Request
run-name: '#${{github.event.pull_request.number}}: "${{github.event.pull_request.title}}" [${{github.actor}}]'
on:
  pull_request:
    branches:
      - dev

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-24.04
    uses: TravelSizedLions/actions/.github/workflows/merge-request.yaml@dev
